### ISSUE TITLE
Некорректное отображение страницы "Корзина"

### ISSUE THREAD

**Issue by stug111** [ivannikitin-com/lustshop#100]
Страница корзины отображается не как все страницы сайта

1) Задний фон не должен быть белым, нужно сделать как на всем сайте
2) Скорей всего придется исправить цвета таблицы, из-за того что они сольются

**Comment by gruzdevas** [comment]
Да, я специально сделала белым фон. На сером не могла подобрать подходящие цвета для таблицы.

**Comment by gruzdevas** [comment]
Сделано.
