### ISSUE TITLE
Исправить высоту изображений в блоке "Блог" как на макете

### ISSUE THREAD

**Issue by stug111** [ivannikitin-com/lustshop#25]
![Снимок экрана 2019-10-11 в 13 59 34](https://user-images.githubusercontent.com/27495069/66631010-8e81cc80-ec2f-11e9-8558-56b43ad98b68.png)

**Comment by gruzdevas** [comment]
Размер изображений настроен. Еще перенесла верхний отступ у текста под картинкой картинке внизу. На случай, когда картинки нет.
