### ISSUE TITLE
Мобильное меню

### ISSUE THREAD

**Issue by stug111** [ivannikitin-com/lustshop#61]
![image](https://user-images.githubusercontent.com/27495069/79311618-eaebde80-7f27-11ea-9427-2dd2e39f26e2.png)

**Comment by stug111** [comment]
Поведение мобильного меню

На пункте который имеет вложенные подпункты должен обрабатываться клик т.е. не переходить по ссылке(использовать preventDefault). По клику раскрываются подпункты и текущему пункту добавляется класс, для подсветки и отображение вложенных пунктов

При клике на другой элемент предыдущий должен закрываться

**Comment by stug111** [comment]
Обсудили что будем делать через классы bootstrap-па добавил [walker](https://github.com/ivannikitin-com/lustshop/pull/63) для расширения классов меню 

Использование (классы по необходимости):
```
wp_nav_menu( array(
    'theme_location'  => 'primary',
    'depth'           => 2, // 1 = no dropdowns, 2 = with dropdowns.
    'container'       => 'div',
    'container_class' => 'collapse navbar-collapse',
    'container_id'    => 'bs-example-navbar-collapse-1',
    'menu_class'      => 'navbar-nav mr-auto',
    'fallback_cb'     => 'WP_Bootstrap_Navwalker::fallback',
    'walker'          => new WP_Bootstrap_Navwalker(),
) );
```

**Comment by gruzdevas** [comment]
Сделано.
