### ISSUE TITLE
Баннер для страницы категорий

### ISSUE THREAD

**Issue by stug111** [ivannikitin-com/lustshop#65]
![image](https://user-images.githubusercontent.com/27495069/79419702-868d5580-7fe1-11ea-96df-dffe36410cda.png)
https://app.zeplin.io/project/5d95bd77cd6cc261bce88756/screen/5d96fb7cb6c1b602564c58c8

**Comment by gruzdevas** [comment]
@stug111 Вадим, кнопку прозрачной делать нельзя - вдруг фон картинки будет светлым, и надпись не будет видна на нем.

**Comment by gruzdevas** [comment]
Все, разобралась. Здесь идет отдельно картинка и отдельно фон,

**Comment by gruzdevas** [comment]
Готово.
