### ISSUE TITLE
Блок описания категории

### ISSUE THREAD

**Issue by stug111** [ivannikitin-com/lustshop#66]
![image](https://user-images.githubusercontent.com/27495069/79419777-acb2f580-7fe1-11ea-9f4b-d6f521b06f5d.png)

https://app.zeplin.io/project/5d95bd77cd6cc261bce88756/screen/5d96ff7157aacc15bd2eb844

**Comment by gruzdevas** [comment]
Задача выполнена за 1,5 ч.
