### ISSUE TITLE
Подключить шрифт Montserrat

### ISSUE THREAD

**Issue by gruzdevas** [ivannikitin-com/lustshop#74]
Этот шрифт есть тут: https://fonts.google.com/specimen/Montserrat
@stug111 Вадим, как мы его подключим?

**Comment by stug111** [comment]
Подключаем локально

**Comment by gruzdevas** [comment]
Я уже не помню, где он использовался. Не могу даже найти. Может без него обойдемся?

**Comment by gruzdevas** [comment]
И в файле шрифтов его нет.
****Основной шрифт — https://fontstorage.com/font/julieta-ulanovsky/montserrat-alternates
Light
Regular
SemiBold

Акцидентный — https://fontstorage.com/font/claus-eggers-srensen/playfair-display
BoldItalic****
