### ISSUE TITLE
Стилизовать страницу "Корзина"

### ISSUE THREAD

**Issue by stug111** [ivannikitin-com/lustshop#80]
Стилизовать страницу "Корзина" как это сделано в теме  storefront
https://themes.woocommerce.com/storefront/cart/

**Comment by gruzdevas** [comment]
@stug111 Почему-то товары в корзину не добавляются.

**Comment by gruzdevas** [comment]
Задача выполнена.

**Comment by gruzdevas** [comment]
Задача заняла 2 ч.
