### ISSUE TITLE
Стилизовать виджет "Блог"

### ISSUE THREAD

**Issue by stug111** [ivannikitin-com/lustshop#85]
`template-parts/components/widgets/post-widget.php` - тут лежит шаблон записи
`inc/widgets/post-widget.php` - тут находится сам виджет, если вдруг понадобиться сделать обертку или добавить какой-то родительский класс, можешь сделать это там

![image](https://user-images.githubusercontent.com/27495069/81059288-6115ac80-8efa-11ea-920c-498fb5601358.png)

**Comment by gruzdevas** [comment]
@stug111 А что у нас с текстом при наведении?

**Comment by gruzdevas** [comment]
Готово.
